import { TRPCError } from "@trpc/server";
import { env } from "~/env";
import type { Session } from "next-auth";
import IORedis from "ioredis";
import { downloadQueue } from "~/server/queue/downloadQueue";
import type { DownloadJobData, DownloadResult } from "~/server/queue/types";
import { removeDownloadedFile } from "./redisService";

const redis = new IORedis({
  host: process.env.REDIS_HOST ?? "localhost",
  port: parseInt(process.env.REDIS_PORT ?? "6379"),
  password: process.env.REDIS_PASSWORD,
  maxRetriesPerRequest: null,
});

export interface YouTubeSearchResult {
  videoId: string;
  title: string;
  channel: string;
  duration: string;
  thumbnail: string;
  confidence: number;
  explicit: boolean;
}

export interface YouTubeSearchInput {
  trackName: string;
  artistName: string;
  albumName?: string;
  durationMs: number;
}

export class YouTubeService {
  private session?: Session; // Make optional for static methods

  constructor(session?: Session) {
    this.session = session;
  }

  private parseYouTubeDuration(duration: string): number {
    const match = /PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/.exec(duration);
    if (!match) return 0;

    const hours = parseInt(match[1] ?? "0");
    const minutes = parseInt(match[2] ?? "0");
    const seconds = parseInt(match[3] ?? "0");

    return hours * 3600 + minutes * 60 + seconds;
  }

  private calculateDurationConfidence(
    spotifyDurationMs: number,
    youtubeDurationSec: number,
  ): number {
    const spotifyDurationSec = Math.floor(spotifyDurationMs / 1000);
    const diff = Math.abs(spotifyDurationSec - youtubeDurationSec);
    const maxDiff = Math.max(spotifyDurationSec, youtubeDurationSec) * 0.1; // 10% tolerance

    return Math.max(0, Math.min(100, 100 - (diff / maxDiff) * 100));
  }

  private isYouTubeContentExplicit(
    title: string,
    channel: string,
    madeForKids?: boolean,
    selfDeclaredMadeForKids?: boolean,
  ): boolean {
    if (madeForKids === true || selfDeclaredMadeForKids === true) {
      return false;
    }

    const explicitKeywords = [
      "explicit",
      "clean",
      "censored",
      "radio edit",
      "tv edit",
    ];
    const lowerTitle = title.toLowerCase();
    const lowerChannel = channel.toLowerCase();

    if (explicitKeywords.some((keyword) => lowerTitle.includes(keyword))) {
      return true;
    }

    if (
      lowerChannel.includes("clean") ||
      lowerChannel.includes("radio") ||
      lowerChannel.includes("tv")
    ) {
      return true;
    }

    return false;
  }

  async search(
    input: YouTubeSearchInput,
  ): Promise<{ matches: YouTubeSearchResult[] }> {
    const apiKey = env.YOUTUBE_API_KEY;
    if (!apiKey) {
      throw new TRPCError({
        code: "INTERNAL_SERVER_ERROR",
        message: "YouTube API key is not configured",
      });
    }

    const searchQuery = `${input.artistName} ${input.trackName} autogenerated`;
    const cacheKey = `youtube:search:${searchQuery}:${input.durationMs}`;

    try {
      const cachedResult = await redis.get(cacheKey);
      if (cachedResult) {
        console.log("YouTube search cache hit for:", searchQuery);
        return JSON.parse(cachedResult) as { matches: YouTubeSearchResult[] };
      }
    } catch (error) {
      console.warn("Redis cache read error:", error);
    }

    console.log("YouTube search cache miss for:", searchQuery);

    // Search for videos
    const searchResponse = await fetch(
      `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(searchQuery)}&type=video&maxResults=5&key=${apiKey}`,
    );

    if (!searchResponse.ok) {
      const errorText = await searchResponse.text();
      console.error("YouTube Search API error:", {
        status: searchResponse.status,
        statusText: searchResponse.statusText,
        body: errorText,
      });

      if (searchResponse.status === 403) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message:
            "YouTube API access denied. Please check your API key and ensure YouTube Data API v3 is enabled.",
        });
      }

      throw new TRPCError({
        code: "INTERNAL_SERVER_ERROR",
        message: `YouTube Search API error: ${searchResponse.status} - ${errorText}`,
      });
    }

    const searchData = (await searchResponse.json()) as {
      items: Array<{
        id: { videoId: string };
        snippet: {
          title: string;
          channelTitle: string;
          thumbnails: { default: { url: string } };
        };
        contentDetails?: { duration: string };
      }>;
    };

    if (!searchData.items || searchData.items.length === 0) {
      return { matches: [] };
    }

    // Get video details
    const videoIds = searchData.items.map((item) => item.id.videoId).join(",");
    const detailsResponse = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?part=contentDetails,status&id=${videoIds}&key=${apiKey}`,
    );

    if (!detailsResponse.ok) {
      const errorText = await detailsResponse.text();
      console.error("YouTube Videos API error:", {
        status: detailsResponse.status,
        statusText: detailsResponse.statusText,
        body: errorText,
      });

      if (detailsResponse.status === 403) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message:
            "YouTube API access denied. Please check your API key and ensure YouTube Data API v3 is enabled.",
        });
      }

      throw new TRPCError({
        code: "INTERNAL_SERVER_ERROR",
        message: `YouTube Videos API error: ${detailsResponse.status} - ${errorText}`,
      });
    }

    const detailsData = (await detailsResponse.json()) as {
      items: Array<{
        id: string;
        contentDetails: { duration: string };
        status: { madeForKids?: boolean; selfDeclaredMadeForKids?: boolean };
      }>;
    };

    // Combine results
    const matches: YouTubeSearchResult[] = searchData.items
      .map((item, index) => {
        const details = detailsData.items?.[index];
        const youtubeDurationSec = details
          ? this.parseYouTubeDuration(details.contentDetails.duration)
          : 0;
        const confidence = this.calculateDurationConfidence(
          input.durationMs,
          youtubeDurationSec,
        );
        const explicit = this.isYouTubeContentExplicit(
          item.snippet.title,
          item.snippet.channelTitle,
          details?.status.madeForKids,
          details?.status.selfDeclaredMadeForKids,
        );

        return {
          videoId: item.id.videoId,
          title: item.snippet.title,
          channel: item.snippet.channelTitle,
          duration: details?.contentDetails.duration ?? "PT0S",
          thumbnail: item.snippet.thumbnails.default.url,
          confidence,
          explicit,
        };
      })
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, 5);

    const result = { matches };

    // Cache for 30 minutes
    try {
      await redis.setex(cacheKey, 1800, JSON.stringify(result));
    } catch (error) {
      console.warn("Redis cache write error:", error);
    }

    return result;
  }

  async downloadTracks(
    tracks: Array<{
      videoId: string;
      trackName: string;
      artistName: string;
      allArtists?: string[];
      artwork?: string;
    }>,
  ): Promise<{
    success: boolean;
    message: string;
    jobs: Array<{
      jobId: string;
      videoId: string;
      trackName: string;
      artistName: string;
      allArtists?: string[];
    }>;
  }> {
    const userId = this.session!.user.id;
    const jobs = [];

    console.log(
      `🎵 downloadTracks called for user ${userId} with ${tracks.length} tracks`,
    );

    if (tracks.length === 0) {
      throw new TRPCError({
        code: "BAD_REQUEST",
        message: "No tracks provided for download",
      });
    }

    if (tracks.length > 50) {
      throw new TRPCError({
        code: "BAD_REQUEST",
        message: "Cannot download more than 50 tracks at once",
      });
    }

    for (const track of tracks) {
      const jobData: DownloadJobData = {
        videoId: track.videoId,
        trackName: track.trackName,
        artistName: track.artistName,
        allArtists: track.allArtists,
        artwork: track.artwork,
        userId,
        jobId: `${userId}-${track.videoId}-${Date.now()}`,
      };

      console.log(
        `📥 Adding job for: ${track.artistName} - ${track.trackName}`,
      );
      if (track.allArtists && track.allArtists.length > 1) {
        console.log(`   All artists: ${track.allArtists.join(", ")}`);
      }

      const job = await downloadQueue.add(
        `download-${track.videoId}`,
        jobData,
        {
          priority: 0,
          delay: 0,
        },
      );

      jobs.push({
        jobId: job.id!,
        videoId: track.videoId,
        trackName: track.trackName,
        artistName: track.artistName,
        allArtists: track.allArtists,
      });
    }

    console.log(`✅ Added ${jobs.length} tracks to download queue`);

    return {
      success: true,
      message: `Added ${jobs.length} tracks to download queue`,
      jobs,
    };
  }

  static async getDownloadStatus(jobIds: string[]): Promise<
    Array<{
      jobId: string;
      status: string;
      progress: number;
      result?: DownloadResult;
      failedReason?: string;
      error?: string;
    }>
  > {
    const jobs = await Promise.all(
      jobIds.map(async (jobId) => {
        try {
          const job = await downloadQueue.getJob(jobId);
          if (!job) {
            return {
              jobId,
              status: "not_found",
              progress: 0,
            };
          }

          const state = await job.getState();
          const progress = job.progress as number;

          return {
            jobId,
            status: state,
            progress,
            result: job.returnvalue as DownloadResult | undefined,
            failedReason: job.failedReason,
          };
        } catch (error) {
          return {
            jobId,
            status: "error",
            progress: 0,
            error: error instanceof Error ? error.message : "Unknown error",
          };
        }
      }),
    );

    return jobs;
  }

  static async cleanupDownloads(downloadIds: string[]): Promise<{
    success: boolean;
    message: string;
    cleanedCount: number;
  }> {
    let cleanedCount = 0;

    for (const downloadId of downloadIds) {
      if (await removeDownloadedFile(downloadId)) {
        cleanedCount++;
      }
    }

    return {
      success: true,
      message: `Cleaned up ${cleanedCount} files`,
      cleanedCount,
    };
  }
}
