import { z } from "zod";

import { env } from "~/env";
import {
  createTRPCRouter,
  protectedProcedure,
} from "~/server/api/trpc";
import { downloadQueue, removeDownloadedFile } from "~/server/queue/downloadQueue";
import type { DownloadJobData } from "~/server/queue/downloadQueue";
import IORedis from 'ioredis';

// Redis instance for caching (reuse from downloadQueue if possible)
const redis = new IORedis({
  host: process.env.REDIS_HOST ?? 'localhost',
  port: parseInt(process.env.REDIS_PORT ?? '6379'),
  password: process.env.REDIS_PASSWORD,
  maxRetriesPerRequest: null,
});

type JobResult = {
  videoId: string;
  trackName: string;
  artistName: string;
  downloadId: string;
  fileSize: number;
  duration: number;
  success: boolean;
  error?: string;
};

interface YouTubeSearchResult {
  videoId: string;
  title: string;
  channel: string;
  duration: string;
  thumbnail: string;
  confidence: number;
  explicit: boolean;
}

interface YouTubeSearchResponse {
  items: Array<{
    id: {
      videoId: string;
    };
    snippet: {
      title: string;
      channelTitle: string;
      thumbnails: {
        default: { url: string };
      };
    };
    contentDetails?: {
      duration: string;
    };
  }>;
}

// Helper function to parse YouTube duration (PT4M13S -> 253 seconds)
function parseYouTubeDuration(duration: string): number {
  const match = /PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/.exec(duration);
  if (!match) return 0;

  const hours = parseInt(match[1] ?? '0');
  const minutes = parseInt(match[2] ?? '0');
  const seconds = parseInt(match[3] ?? '0');

  return hours * 3600 + minutes * 60 + seconds;
}

// Helper function to calculate duration match confidence
function calculateDurationConfidence(spotifyDurationMs: number, youtubeDurationSec: number): number {
  const spotifyDurationSec = Math.floor(spotifyDurationMs / 1000);
  const diff = Math.abs(spotifyDurationSec - youtubeDurationSec);
  const maxDiff = Math.max(spotifyDurationSec, youtubeDurationSec) * 0.1; // 10% tolerance

  return Math.max(0, Math.min(100, 100 - (diff / maxDiff) * 100));
}

// Helper function to determine if YouTube content is explicit
function isYouTubeContentExplicit(title: string, channel: string, madeForKids?: boolean, selfDeclaredMadeForKids?: boolean): boolean {
  // If explicitly marked as made for kids, it's not explicit
  if (madeForKids === true || selfDeclaredMadeForKids === true) {
    return false;
  }

  // Check for explicit keywords in title or channel name
  const explicitKeywords = ['explicit', 'clean', 'censored', 'radio edit', 'tv edit'];
  const lowerTitle = title.toLowerCase();
  const lowerChannel = channel.toLowerCase();

  // If title contains explicit keywords, likely explicit
  if (explicitKeywords.some(keyword => lowerTitle.includes(keyword))) {
    return true;
  }

  // If channel name suggests clean/radio versions, might be explicit
  if (lowerChannel.includes('clean') || lowerChannel.includes('radio') || lowerChannel.includes('tv')) {
    return true;
  }

  // Default to false for regular content (YouTube doesn't have explicit flags like Spotify)
  return false;
}

export const youtubeRouter = createTRPCRouter({
  searchYouTube: protectedProcedure
    .input(
      z.object({
        trackName: z.string(),
        artistName: z.string(),
        albumName: z.string().optional(),
        durationMs: z.number(),
      })
    )
    .query(async ({ input }) => {
      const apiKey = env.YOUTUBE_API_KEY;

      if (!apiKey) {
        throw new Error('YouTube API key is not configured');
      }

      // Create search query combining track metadata
      const searchQuery = `${input.artistName} ${input.trackName} autogenerated`;

      // Create cache key for this search
      const cacheKey = `youtube:search:${searchQuery}:${input.durationMs}`;

      try {
        // Check cache first (30 minute TTL)
        const cachedResult = await redis.get(cacheKey);
        if (cachedResult) {
          console.log('YouTube search cache hit for:', searchQuery);
          // eslint-disable-next-line @typescript-eslint/no-unsafe-return
          return JSON.parse(cachedResult);
        }
      } catch (error) {
        console.warn('Redis cache read error:', error);
        // Continue without cache
      }

      console.log('YouTube search cache miss for:', searchQuery);

      // First, search for videos (reduced from 10 to 5 since we only return top 5)
      const searchResponse = await fetch(
        `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(searchQuery)}&type=video&maxResults=5&key=${apiKey}`
      );

      if (!searchResponse.ok) {
        const errorText = await searchResponse.text();
        console.error('YouTube Search API error:', {
          status: searchResponse.status,
          statusText: searchResponse.statusText,
          body: errorText,
        });

        if (searchResponse.status === 403) {
          throw new Error('YouTube API access denied. Please check your API key and ensure YouTube Data API v3 is enabled.');
        }

        throw new Error(`YouTube Search API error: ${searchResponse.status} - ${errorText}`);
      }

      const searchData = await searchResponse.json() as YouTubeSearchResponse;

      if (!searchData.items || searchData.items.length === 0) {
        return { matches: [] };
      }

      // Get video details including duration and content rating for the found videos
      const videoIds = searchData.items.map(item => item.id.videoId).join(',');
      const detailsResponse = await fetch(
        `https://www.googleapis.com/youtube/v3/videos?part=contentDetails,status&id=${videoIds}&key=${apiKey}`
      );

      if (!detailsResponse.ok) {
        const errorText = await detailsResponse.text();
        console.error('YouTube Videos API error:', {
          status: detailsResponse.status,
          statusText: detailsResponse.statusText,
          body: errorText,
        });

        if (detailsResponse.status === 403) {
          throw new Error('YouTube API access denied. Please check your API key and ensure YouTube Data API v3 is enabled.');
        }

        throw new Error(`YouTube Videos API error: ${detailsResponse.status} - ${errorText}`);
      }

      const detailsData = await detailsResponse.json() as { items: Array<{ id: string; contentDetails: { duration: string }; status: { madeForKids?: boolean; selfDeclaredMadeForKids?: boolean } }> };

      // Combine search results with duration details
      const matches: YouTubeSearchResult[] = searchData.items
        .map((item, index) => {
          const details = detailsData.items?.[index];
          const youtubeDurationSec = details ? parseYouTubeDuration(details.contentDetails.duration) : 0;
          const confidence = calculateDurationConfidence(input.durationMs, youtubeDurationSec);
          const explicit = isYouTubeContentExplicit(
            item.snippet.title,
            item.snippet.channelTitle,
            details?.status.madeForKids,
            details?.status.selfDeclaredMadeForKids
          );

          return {
            videoId: item.id.videoId,
            title: item.snippet.title,
            channel: item.snippet.channelTitle,
            duration: details?.contentDetails.duration ?? 'PT0S',
            thumbnail: item.snippet.thumbnails.default.url,
            confidence,
            explicit,
          };
        })
        .sort((a, b) => b.confidence - a.confidence) // Sort by confidence descending
        .slice(0, 5); // Return top 5 matches

      const result = { matches };

      // Cache the result for 30 minutes
      try {
        await redis.setex(cacheKey, 1800, JSON.stringify(result)); // 30 minutes TTL
      } catch (error) {
        console.warn('Redis cache write error:', error);
        // Continue without caching
      }

      return result;
    }),

  downloadTracks: protectedProcedure
    .input(
      z.object({
        tracks: z.array(
          z.object({
            videoId: z.string(),
            trackName: z.string(),
            artistName: z.string(),
            allArtists: z.array(z.string()).optional(), // Array of all artists from Spotify
          })
        ),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const userId = ctx.session.user.id;
      const jobs = [];

      console.log(`🎵 downloadTracks called for user ${userId} with ${input.tracks.length} tracks`);

      // Validate input
      if (input.tracks.length === 0) {
        throw new Error("No tracks provided for download");
      }

      if (input.tracks.length > 50) {
        throw new Error("Cannot download more than 50 tracks at once");
      }

      // Add each track to the download queue
      for (const track of input.tracks) {
        const jobData: DownloadJobData = {
          videoId: track.videoId,
          trackName: track.trackName,
          artistName: track.artistName,
          allArtists: track.allArtists,
          userId,
          jobId: `${userId}-${track.videoId}-${Date.now()}`,
        };

        console.log(`📥 Adding job for: ${track.artistName} - ${track.trackName}`);
        if (track.allArtists && track.allArtists.length > 1) {
          console.log(`   All artists: ${track.allArtists.join(', ')}`);
        }

        const job = await downloadQueue.add(
          `download-${track.videoId}`,
          jobData,
          {
            priority: 0,
            delay: 0,
          }
        );

        jobs.push({
          jobId: job.id,
          videoId: track.videoId,
          trackName: track.trackName,
          artistName: track.artistName,
        });
      }

      console.log(`✅ Added ${jobs.length} tracks to download queue`);

      return {
        success: true,
        message: `Added ${jobs.length} tracks to download queue`,
        jobs,
      };
    }),

  getDownloadStatus: protectedProcedure
    .input(
      z.object({
        jobIds: z.array(z.string()),
      })
    )
    .query(async ({ input }) => {
      const jobs = await Promise.all(
        input.jobIds.map(async (jobId) => {
          try {
            const job = await downloadQueue.getJob(jobId);
            if (!job) {
              return {
                jobId,
                status: 'not_found',
                progress: 0,
              };
            }

            const state = await job.getState();
            const progress = job.progress as number;

            return {
              jobId,
              status: state,
              progress,
              result: job.returnvalue as JobResult | undefined,
              failedReason: job.failedReason,
            };
          } catch (error) {
            return {
              jobId,
              status: 'error',
              progress: 0,
              error: error instanceof Error ? error.message : 'Unknown error',
            };
          }
        })
      );

      return { jobs };
    }),

  cleanupDownloads: protectedProcedure
    .input(
      z.object({
        downloadIds: z.array(z.string()),
      })
    )
    .mutation(async ({ input }) => {
      let cleanedCount = 0;

      for (const downloadId of input.downloadIds) {
        if (await removeDownloadedFile(downloadId)) {
          cleanedCount++;
        }
      }

      return {
        success: true,
        message: `Cleaned up ${cleanedCount} files`,
        cleanedCount,
      };
    }),
});